### ISSUE TITLE
작업물 논리삭제시 챌린지의 참여자에서 제외되게 수정

### ISSUE THREAD

**Issue by taeyeonkim94** [2-Docthru-team1/2-Docthru-team1-BE#215]
## 작업 사항 설명
작업물 논리삭제시 챌린지의 참여자에서 제외되게 수정
## TO-DO

- [ ] 작업물 논리삭제 시 챌린지의 참여자에서 제외되게 수정

**Comment by alscksdlek** [comment]
오오 화이팅입니다!
